# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_on', models.DateField(auto_now_add=True)),
                ('dishes', models.TextField(default='')),
                ('anon_dishes', models.TextField(default='')),
            ],
            options={
                'ordering': ['-made_on'],
            },
        ),
        migrations.CreateModel(
            name='PagesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_page_offer', models.CharField(default='', max_length=300)),
                ('main_page_offer_text', models.TextField(default='')),
                ('profile_page_show_bonus', models.BooleanField(default=False)),
            ],
        ),
    ]
