# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='made_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='user.Profile'),
        ),
        migrations.AddField(
            model_name='notification',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Order'),
        ),
        migrations.AddField(
            model_name='notification',
            name='profiles',
            field=models.ManyToManyField(related_name='notifications', to='user.Profile'),
        ),
    ]
